name: CICD pipline

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Node jobs
        uses: actions/setup-node@v4
        with:
          node-version: '22'
        
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: jest --testResultsProcessor=jest-junit --outputFile=junit.xml

      - name: Upload test results 
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./junit.xml
          
        
  
  deploy:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: ./junit.xml

      - name: Display test results
        run: cat ./junit.xml


      - name: Install The Packages
        run: npm install

      - name: Start The Application
        run: |
          ls -a
          pm2 status

          #* delete node-app process
          pm2 delete node-app || true

          #* Create a background process name node-app
          pm2 start "npm start" --name="node-app"

          #* Save the process
          pm2 save

      
